# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  DisabledByDefault: false
  TargetRubyVersion: 2.5
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - 'node_modules/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

# Redefined

Metrics/LineLength:
  Max: 120

# Disabled

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'Guardfile'

Lint/AssignmentInCondition:
  Exclude:
    - 'bin/spring'
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/*'
